// Generated by CoffeeScript 1.3.3
(function() {
  var SkeletonNode;

  SkeletonNode = (function() {

    function SkeletonNode(ctx) {
      this.jointAngle = 0;
      this.x = 0;
      this.y = 0;
      this.ctx = ctx;
      this.parent = null;
      this.children = [];
    }

    SkeletonNode.prototype.renderChildren = function(ctx) {
      var child, _i, _len, _ref, _results;
      _ref = this.children;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        child = _ref[_i];
        _results.push(child.render(ctx));
      }
      return _results;
    };

    SkeletonNode.prototype.addChild = function(node) {
      node.parent = this;
      return this.children.push(node);
    };

    SkeletonNode.prototype.render = function(ctx) {
      ctx.save();
      ctx.fillStyle = "rgba(0,0,0,1)";
      ctx.strokeStyle = "#000";
      if (this.parent != null) {
        ctx.beginPath();
        ctx.moveTo(this.x, this.y);
        ctx.lineTo(0, 0);
        ctx.stroke();
      }
      ctx.translate(this.x, this.y);
      ctx.rotate(this.jointAngle * (Math.PI / 180));
      ctx.beginPath();
      ctx.arc(0, 0, 5, 0, Math.PI * 2, true);
      ctx.fill();
      this.renderChildren(ctx);
      return ctx.restore();
    };

    return SkeletonNode;

  })();

  window.SkeletonNode = SkeletonNode;

}).call(this);
